### PR TITLE
Updates implementing our latest discussions.

### PR DESCRIPTION
**Pull request by Smeds**
### This PR:

Refactoring: Code updates, mostly changes to follow our latest discussions.

### Review and tests: 
- [x] Tests pass
- [ ] Code review

### CODE REVIEW

**Review by jonca79 — COMMENTED** [review]
Borde det inte vara en resource.schema.yaml också

**Comment by Smeds** [comment]
> Borde det inte vara en resource.schema.yaml också

absolut!

**Review by jonca79 — COMMENTED** [review]
Remove dag.svgsnakemake?

**Review by jonca79 — CHANGES_REQUESTED** [review]
Remove  dag.svgsnakemake under .tests/integration

**Review by jonca79 — APPROVED** [review]

**Comment by Smeds** [comment]
> Remove dag.svgsnakemake under .tests/integration
 klart

**Pull request merged**
